//------------------------------------------------------------------------
// Copyright(c) 2023 Dsus.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Colores.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Colores VST3 (64Bit)"
#else
#define stringFileDescription	"Colores VST3"
#endif
#define stringCompanyName		"Dsus\0"
#define stringLegalCopyright	"Copyright(c) 2023 Dsus."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
